#!/usr/bin/env bash
# Generates a .env file with random secrets pre-filled.
# Keys that require external setup are left as placeholders.
#
# Usage: bash gen-env.sh

set -euo pipefail

DEST=".env"

if [[ -f "$DEST" ]]; then
  echo "error: $DEST already exists. Remove it first if you want to regenerate."
  exit 1
fi

# ── helpers ───────────────────────────────────────────────────────────────────

# Random base64url string of N bytes (URL-safe, no padding)
rand_b64() { openssl rand -base64 "$1" | tr '+/' '-_' | tr -d '=\n'; }

# Random hex string of N bytes (produces 2*N hex chars)
rand_hex() { openssl rand -hex "$1"; }

# ── generate ──────────────────────────────────────────────────────────────────

cat > "$DEST" <<EOF
# Generated by gen-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# chmod 600 .env — do not commit this file

# ── Anthropic ─────────────────────────────────────────────────────────────────
# Paste your key from https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY=sk-ant-REPLACE_ME

# ── Core infrastructure ───────────────────────────────────────────────────────
POSTGRES_PASSWORD=$(rand_b64 24)
MCP_POSTGRES_PASSWORD=$(rand_b64 24)
REDIS_PASSWORD=$(rand_b64 24)
N8N_ENCRYPTION_KEY=$(rand_b64 24)
SEARXNG_SECRET_KEY=$(rand_hex 32)

# ── Langfuse — internal service credentials ───────────────────────────────────
LANGFUSE_DB_PASSWORD=$(rand_b64 24)
LANGFUSE_NEXTAUTH_SECRET=$(rand_b64 32)
LANGFUSE_SALT=$(rand_b64 24)
LANGFUSE_ENCRYPTION_KEY=$(rand_hex 32)

# External URL for LangFuse — must match your reverse proxy (required for login)
LANGFUSE_URL=https://REPLACE_ME_langfuse_domain

# ── Langfuse — API keys ───────────────────────────────────────────────────────
# Create a project at http://localhost:3004, then paste the keys here.
LANGFUSE_PUBLIC_KEY=pk-lf-REPLACE_ME
LANGFUSE_SECRET_KEY=sk-lf-REPLACE_ME

# ── Browserless ───────────────────────────────────────────────────────────────
BROWSERLESS_TOKEN=$(rand_b64 24)

# ── Gitea ─────────────────────────────────────────────────────────────────────
# External URL for Gitea — must match your reverse proxy (sets clone URLs)
GITEA_ROOT_URL=https://REPLACE_ME_gitea_domain
# Create a token at http://localhost:3003 → Settings → Applications
GITEA_TOKEN=REPLACE_ME

# ── Garage S3 ─────────────────────────────────────────────────────────────────
# Run 'bash garage/init.sh' after first start, then paste the output here.
GARAGE_ACCESS_KEY_ID=REPLACE_ME
GARAGE_SECRET_ACCESS_KEY=REPLACE_ME

# ── claude-worker ─────────────────────────────────────────────────────────────
CLAUDE_WORKER_TOKEN=$(rand_b64 24)

# ── Optional claude-worker overrides ──────────────────────────────────────────
# DEFAULT_MAX_ITERATIONS=20
# DEFAULT_COMPLETION_PROMISE=RALPH_COMPLETE
# CLAUDE_TIMEOUT_MS=600000
EOF

chmod 600 "$DEST"

echo "Created $DEST (chmod 600)"
echo ""
echo "Still needs manual input:"
echo "  ANTHROPIC_API_KEY        — https://console.anthropic.com/settings/keys"
echo "  LANGFUSE_URL             — external URL for your LangFuse instance"
echo "  LANGFUSE_PUBLIC_KEY      — create project at http://localhost:3004"
echo "  LANGFUSE_SECRET_KEY      — same"
echo "  GITEA_ROOT_URL           — external URL for your Gitea instance"
echo "  GITEA_TOKEN              — http://localhost:3003 → Settings → Applications"
echo "  GARAGE_ACCESS_KEY_ID     — run bash garage/init.sh after first start"
echo "  GARAGE_SECRET_ACCESS_KEY — same"
